### ISSUE TITLE
2017/7/21

### ISSUE THREAD

**Issue by hefengly** [2017-TopView-FrontEnd/JavaScript-For-Us#13]
## 今天学了什么
- todo  1.0
## 遇到了什么难以解决的问题
- 调了大半天的bug,有点怀疑人生。
## 明天的计划打算
- 高设 第十四章
- todo
## 今天的感受
- 困...
- 累。。
- 不过调好程序后，很爽。。
- 我今天要早点回去睡觉了，很困

**Comment by qingtianiii** [comment]
## 今天学了什么
- 高设 第二十二章、第二十四章
- todo
- 玩了下JSON server 
## 遇到了什么难以解决的问题
- 一bug未平一bug又起
## 明天的计划打算
- 看ES6
- todo
- 路由....器？
## 今天的感受
- 唉，又帅了

**Comment by CINDY420** [comment]
## 今天学了什么
- 高设 第十六章
- todo
- 看了下JSON server 
## 遇到了什么难以解决的问题
## 明天的计划打算
- 高设
- todo
## 今天的感受

**Comment by JianLux** [comment]
## 今天学了什么
- todo。。。。
- 高设二十章，三页！！\~\(≧▽≦)/\~

## 遇到了什么难以解决的问题
- bug,bug,全是bug

## 明天的计划打算
- 高设 二十章，二十三章

## 今天的感受
- 头晕脑胀。。。
- 顺手不小心删了手机里最大的一个文件夹，所有文档都没了。。。手机瞬间就有内存了，还可以下游戏了~:worried:
- 发个表情还要用斜杠(┬＿┬)

**Comment by kimZLeung** [comment]
- 有bug是好事情呀，没bug还有什么意思
- 这周分享会感觉要成为比惨会...比比谁的bug比较坑

**Comment by qingtianiii** [comment]
又岩喔
