### ISSUE TITLE
2017/7/10

### ISSUE THREAD

**Issue by JianLux** [2017-TopView-FrontEnd/JavaScript-For-Us#2]
## 今天学了什么
- 高设3.1到3.4
- FreeCodeCamp部分题目
- github本地仓库推东西到远程仓库最简单的步骤？_(:зゝ∠)_

## 遇到了什么难以解决的问题
- github仓库改了仓库名。。。怎么同步本地仓库。。。  
（已解决，把本地的删掉再clone了一个到本地_(:зゝ∠)_）

## 明天的计划打算
- 高设还要看前言？明天看前言，做第一二章的笔记，学完第三章
- 学完HTML5 & CSS, Responsive Design with Bootstrap 部分

## 今天的感受
- 空调很冷吗？还好啦~:smile:
- 早起真的难受:sob:
- 第一天有点小兴奋ヾ(o◕∀◕)ﾉヾ
- 以后吃饭要积极，早点走╭(′▽`)╯，不然饭堂都没吃的啦
- 雨下的真的很大。。。

**Comment by hefengly** [comment]
## 今天学了什么
- 高设第一章到第三章
- 学完了FreeCodeCamp中的HTML5 & CSS

## 遇到了什么难以解决的问题
坐太久很累。。。似乎很难解决
## 明天的计划打算
- 看高设，多做笔记
- 学完 Responsive Design with Bootstrap 部分

## 今天的感受
- 空调很冷。
- 以后要早点吃去饭，不然饭堂只有剩菜剩饭，今天的晚餐就是，极度难受。
- 一直对着电脑和书，头有点晕。。。以后慢慢习惯
- 刚刚每人发了工作室门钥匙，好激动好激动。

**Comment by CINDY420** [comment]
# 今天学了什么
- 高设3.4章
- flex布局 还玩了小青蛙
- grid布局  
- FreeCodeCamp部分题目

## 遇到了什么难以解决的问题
- 玩grid那个游戏的时候没搞懂grid-template-rows.....

## 明天的计划打算
- 高设继续看
- 看git
- 继续 Responsive Design with Bootstrap 

## 今天的感受
挺累的....嗯.....

**Comment by qingtianiii** [comment]
## 今天学了什么
- 高设第一章到第三章一半
- FreeCodeCamp的html5 & css 差不多做完
## 遇到了什么难以解决的问题
- label语句的用法不太看不懂
## 明天的计划打算
- 高设学完第三章，第四章
- FreeCodeCamp 完成 html5 & css ;还有完成部分 Responsive Design with Bootstrap
- 玩玩FlexboxFroggy，学flex布局
## 今天的感受
- 怎么感觉比做考核的时候还累。。。继续加油~~
- 感觉拿到了钥匙，啧啧啧，莫名有种被认可的感觉。

**Comment by wuyupeng123** [comment]
## 今天学了什么
- 把高程的第三章看了一部分
- 了解了一下ECMAScript与javaScript的联系
- 刚刚学会用markdown做笔记

## 遇到了什么难以解决的问题
空调太冷，忘记带衣服了

## 明天的计划打算
- 看完高程的第三章
- 学习如何把项目推到仓库
- 学习Free Code Camp ： Getting Started, HTML5 & CSS




## 今天的感受
- 困
- 冷
- 只想睡觉

**Comment by AymaxLi** [comment]
颜文字贼溜Σ(っ °Д °;)っ

**Comment by kimZLeung** [comment]
- label语句是什么 = =
- grid-template-rows的话，明天杰神教你 😆 
- 坐久了多出去走走可以
- 明天记得带衣服 👚 
- 遇到问题后，勤于用搜索引擎哦~ 👍

**Comment by cristianoro7** [comment]
caicai :athletic_shoe:
