### ISSUE TITLE
2017/7/13

### ISSUE THREAD

**Issue by CINDY420** [2017-TopView-FrontEnd/JavaScript-For-Us#5]
## 今天学了什么
- 高设 第七八章
- git教程 时光机穿梭/远程仓库
- js执行机制的文章
## 遇到了什么难以解决的问题
- 没搞懂查询字符串参数
## 明天的计划打算
- 看高设
## 今天的感受
- 没什么感受

**Comment by qingtianiii** [comment]
## 今天学了什么
- 廖雪峰的Git教程：时光机穿梭，远程仓库
- 高设 第六、七、八章
- JS的一些执行机制
## 遇到了什么难以解决的问题
- 写js的时候，有必要用严格模式吗?
- 有时搞不懂this到底指的是哪个对象
- 为啥感觉，没啥demo好敲的...一点都不尴尬
- 网速有点慢啊...
## 明天的计划打算
- 当条咸鱼
- 高设 第九、十章部分吧
- Try jQuery 课程部分内容
- FreeCodeCamp jQuery部分内容
## 今天的感受
- 今天就比较有意思了，具体内容问楼下

**Comment by wuyupeng123** [comment]
## 今天学了什么
- 高设 第五章 第六章一部分

## 遇到了什么难以解决的问题

## 明天的计划打算
- 第六章
## 今天的感受
- 沉迷高设，无法自拔

**Comment by hefengly** [comment]
## 今天学了什么
- 高设第六章（还是不太懂）
- git教程一部分
- freeCodeCamp的一部分
## 遇到了什么难以解决的问题
- apply(),call()有点迷，继承有点迷
## 明天的计划打算
- 看高设，看github
## 今天的感受
- 感觉落下很多进度。。。

**Comment by JianLux** [comment]
## 今天学了什么
- 高设第六章，第五章部分
- 大概看了调试 JavaScript。。。。 
- 廖雪峰的Git教程

## 遇到了什么难以解决的问题
- 难以解决的问题。。。

## 明天的计划打算
- 第五章
- Object Oriented and Functional Programming 部分

## 今天的感受
- 不困！

**Comment by kimZLeung** [comment]
- 网上有`this`广为流传的传说中的四种绑定方式，尝试了解一下吧
- JS中的`this`是比较复杂的问题，这个可以慢慢理解
- 查询字符串参数...就是发起请求时同时会带过去给服务器端的参数，具体可以这周末说一下。
- 大家都好像看得有点迷惘。第一次看继承和原型链会是有点懵逼。以后还得再看一次好好理解一下的，毕竟是基础。
